spring.output.ansi.enabled: always

logging:
    level:
        root: WARN
        com.elderbyte: ${LOG_LEVEL:INFO}

kafka:
  client:
    enabled: true
    servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      transaction.id: demo-app
    consumer:
      enabled: true
      pollTimeout: 3000
    topics:
      - name: _demo.cdc.orders.order
        partitions: 1
        cleanUpPolicy: delete
        retention: 24h
      - name: _demo.cdc.orders.item
        partitions: 1
        cleanUpPolicy: delete
        retention: 24h
